site_name: Auburn Robotics Wiki
site_url: https://auburn-robotics-wiki.pages.dev
# repo_url: https://github.com/undonepotato/auburn-robotics-wiki
edit_uri: https://github.com/undonepotato/auburn-robotics-wiki/edit/main/docs/

nav:
  - Welcome: index.md
  - About: about.md
  - Design:
      - Intro to VEX Design: design/intro-to-vex-design.md
  - Hardware and Building:
      - Intro to VEX Building: building/intro-to-vex-building.md
      - Building Habits and Techniques: building/building-habits.md
  - Software and Programming:
      - Intro to VEX Programming: programming/intro-to-vex-programming.md
      - Programming Languages: programming/programming-languages.md
  - Driving and Strategy:
      - Intro to VEX Driving: driving/intro-to-vex-driving.md
  - Documentation and Notebooking:
      - Intro to VEX Notebooking: notebooking/intro-to-vex-notebooking.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye
  font:
    text: IBM Plex Sans
    code: false
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra:
  analytics:
    provider: google
    property: G-BMFXD4Z82T
  consent:
    title: Cookies
    description: >-
      This site uses cookies to recognize and save repeated visits and
      preferences. Analytics are also gathered to see what is most effective and
      widely used, which helps make the wiki better!
    actions:
      - accept
      - reject
      - manage
  social:
    - icon: fontawesome/brands/github
      name: Auburn Robotics Wiki repo
      link: https://github.com/undonepotato/auburn-robotics-wiki
copyright:
  This wiki is licensed under a <a id="copyright-notice"
  href=https://creativecommons.org/licenses/by-sa/4.0/>Creative Commons
  Attribution-ShareAlike 4.0 International</a> license.
